### PR TITLE
Implemented PUT support for updating a resource

### PR DESCRIPTION
**Pull request by iakovosk**
implemented PUT support for updating a resource

### CODE REVIEW

**Comment by nikokon** [comment]
Travis build fails, you should pull the latest develop into your branch so that you have a branch based on the latest develop... If you don't know how to do this, ask someone in your team ;) 
Also: The different erlang:display-messages are a bit uninforming if they're used for debugging purposes...

**Comment by iakovosk** [comment]
Yes, Travis build fails but this is because I started from and asked to merge with the Sprint3.change-backend-ES branch which is on an early stage and it's far from being merged with the develop branch.

**Comment by nikokon** [comment]
header should be -include_lib("webmachine.hrl"). and not "webmachine/include..."
Also: -compile(export_all) is bad practice... you should specifically state all functions the module exposes.
the erlang:display("got here1/2"). are a bit unclear... either remove them or change the print so that it says something about why it's printing... :)

**Comment by nikokon** [comment]
And travis is failing because you don't have the .travis.yml file that is in develop... so it defaults and tries to build the project as a ruby project.... you could avoid this by merging the latest develop into you local branch... I THINK you can do this by:
git pull origin develop:<the_name_of_your_local_branch>

**Comment by nikokon** [comment]
git pull origin develop:your_branch_name

**Pull request merged**
